#################
# Redis Instance
#################

output "this_redis_instance_id" {
  description = "This redis instance id."
  value       = local.this_instance_id
}

output "this_redis_instance_name" {
  description = "This redis instance name."
  value       = concat(alicloud_kvstore_instance.this.*.instance_name, [""])[0]
}

output "this_redis_instance_class" {
  description = "This redis instance class."
  value       = concat(alicloud_kvstore_instance.this.*.instance_class, [""])[0]
}
output "this_redis_instance_availability_zone" {
  description = "The availability zone in which redis instance."
  value       = concat(alicloud_kvstore_instance.this.*.availability_zone, [""])[0]
}

output "this_redis_instance_charge_type" {
  description = "This redis instance instance charge type."
  value       = concat(alicloud_kvstore_instance.this.*.instance_charge_type, [""])[0]
}

output "this_redis_instance_period" {
  description = "The duration that you will buy DB instance."
  value       = concat(alicloud_kvstore_instance.this.*.period, [""])[0]
}
output "this_redis_instance_auto_renew" {
  description = "Whether to renewal a DB instance automatically or not."
  value       = concat(alicloud_kvstore_instance.this.*.auto_renew, [""])[0]
}
output "this_redis_instance_auto_renew_period" {
  description = "Auto-renewal period of an instance, in the unit of the month."
  value       = concat(alicloud_kvstore_instance.this.*.auto_renew_period, [""])[0]
}

output "this_redis_instance_type" {
  description = "This redis instance type."
  value       = concat(alicloud_kvstore_instance.this.*.instance_type, [""])[0]
}
output "this_redis_instance_vswitch_id" {
  description = "The id of vswitch in which redis instance."
  value       = concat(alicloud_kvstore_instance.this.*.vswitch_id, [""])[0]
}

output "this_redis_instance_engine_version" {
  description = "This redis instance engine version ."
  value       = concat(alicloud_kvstore_instance.this.*.engine_version, [""])[0]
}

output "this_redis_instance_private_ip" {
  description = "Set the instance's private IP."
  value       = concat(alicloud_kvstore_instance.this.*.private_ip, [""])[0]
}

output "this_redis_instance_backup_id" {
  description = "If an instance created based on a backup set generated by another instance is valid, this parameter indicates the ID of the generated backup set."
  value       = concat(alicloud_kvstore_instance.this.*.backup_id, [""])[0]
}

output "this_redis_instance_tags" {
  description = "A mapping of tags to assign to the redis instance resource."
  value       = alicloud_kvstore_instance.this.*.tags
}
output "this_redis_instance_security_ips" {
  description = "List of IP addresses allowed to access all redis of an instance."
  value       = alicloud_kvstore_instance.this.*.security_ips
}
output "this_redis_instance_vpc_auth_mode" {
  description = "Whether to renewal a DB instance automatically or not."
  value       = concat(alicloud_kvstore_instance.this.*.vpc_auth_mode, [""])[0]
}
output "this_redis_instance_maintain_start_time" {
  description = "The start time of the operation and maintenance time period of the instance."
  value       = concat(alicloud_kvstore_instance.this.*.maintain_start_time, [""])[0]
}
output "this_redis_instance_maintain_end_time" {
  ddescription = "The end time of the operation and maintenance time period of the instance."
  value        = concat(alicloud_kvstore_instance.this.*.maintain_end_time, [""])[0]
}
#################
# Redis Account
#################

output "this_redis_instance_account_name" {
  description = "This Redis instance account name."
  value       = module.accounts.this_redis_instance_account_name
}

################
#Backup policy
################

output "this_redis_instance_backup_policy_backup_period" {
  description = "This Redis instance backup policy backup period."
  value       = alicloud_kvstore_backup_policy.this.*.backup_period
}

output "this_redis_instance_backup_policy_backup_time" {
  description = "This Redis instance backup policy backup time."
  value       = concat(alicloud_kvstore_backup_policy.this.*.backup_time, [""])[0]
}