#################
# Redis Instance
#################

output "this_redis_instance_id" {
  description = "This redis instance id."
  value       = module.redis_example.this_redis_instance_id
}

output "this_redis_instance_name" {
  description = "This redis instance name."
  value       = module.redis_example.this_redis_instance_name
}

output "this_redis_instance_class" {
  description = "This redis instance class."
  value       = module.redis_example.this_redis_instance_class
}
output "this_redis_instance_availability_zone" {
  description = "The availability zone in which redis instance."
  value       = module.redis_example.this_redis_instance_availability_zone
}

output "this_redis_instance_charge_type" {
  description = "This redis instance availability charge type."
  value       = module.redis_example.this_redis_instance_charge_type
}

output "this_redis_instance_period" {
  description = "The duration that you will buy DB instance."
  value       = module.redis_example.this_redis_instance_auto_renew_period
}

output "this_redis_instance_auto_renew" {
  description = "Whether to renewal a DB instance automatically or not."
  value       = module.redis_example.this_redis_instance_auto_renew
}

output "this_redis_instance_auto_renew_period" {
  description = "Auto-renewal period of an instance, in the unit of the month."
  value       = module.redis_example.this_redis_instance_auto_renew_period
}

output "this_redis_instance_type" {
  description = "This redis instance type."
  value       = module.redis_example.this_redis_instance_type
}
output "this_redis_instance_vswitch_id" {
  description = "The id of vswitch in which redis instance."
  value       = module.redis_example.this_redis_instance_vswitch_id
}

output "this_redis_instance_engine_version" {
  description = "This redis instance engine version ."
  value       = module.redis_example.this_redis_instance_engine_version
}

output "this_redis_instance_private_ip" {
  description = "Set the instance's private IP."
  value       = module.redis_example.this_redis_instance_private_ip
}

output "this_redis_instance_backup_id" {
  description = "If an instance created based on a backup set generated by another instance is valid, this parameter indicates the ID of the generated backup set."
  value       = module.redis_example.this_redis_instance_backup_id
}

output "this_redis_instance_tags" {
  description = "A mapping of tags to assign to the redis instance resource."
  value       = module.redis_example.this_redis_instance_tags
}
output "this_redis_instance_security_ips" {
  description = "List of IP addresses allowed to access all redis of an instance."
  value       = module.redis_example.this_redis_instance_security_ips
}
output "this_redis_instance_vpc_auth_mode" {
  description = "Whether to renewal a DB instance automatically or not."
  value       = module.redis_example.this_redis_instance_vpc_auth_mode
}
output "this_redis_instance_maintain_start_time" {
  description = "The start time of the operation and maintenance time period of the instance."
  value       = module.redis_example.this_redis_instance_maintain_start_time
}
output "this_redis_instance_maintain_end_time" {
  ddescription = "The end time of the operation and maintenance time period of the instance."
  value        = module.redis_example.this_redis_instance_maintain_end_time
}

#################
# Redis Account
#################

output "this_redis_instance_account_name" {
  description = "This Redis instance account name."
  value       = module.redis_example.this_redis_instance_account_name
}

########################
# Redis backup policy
########################

output "this_redis_instance_backup_policy_backup_period" {
  description = "This Redis instance backup policy backup period."
  value       = module.redis_example.this_redis_instance_backup_policy_backup_period
}

output "this_redis_instance_backup_policy_backup_time" {
  description = "This Redis instance backup policy backup time."
  value       = module.redis_example.this_redis_instance_backup_policy_backup_time
}